version: '3.7'

services:
  flispi-frontend:
    container_name: flispi-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/home/react/app'
      - '/home/react/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_PROD_API_URL=${REACT_APP_PROD_API_URL}
      - REACT_APP_NODE_ENV=${REACT_APP_NODE_ENV}
